stages:
  - build
  - delivery
  - deploy
  #- test

variables:
  TEST_SERVER: $SERVER_USER@$TEST_SERVER_IP
  PROD_SERVER: $SERVER_USER@$PROD_SERVER_IP

services:
  - docker:dind

.build: &build
  stage: build
  tags:
    - ai-docker
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

.delivery: &delivery
  stage: delivery
  tags:
    - ai-docker
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_KEY" | base64 -d)
    - 'mkdir -p ~/.ssh'
    - 'chmod 700 ~/.ssh'
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - ssh-keyscan $TEST_SERVER_IP >> ~/.ssh/known_hosts

.deploy: &deploy
  stage: deploy
  tags:
    - ai-docker
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_KEY" | base64 -d)
    - 'mkdir -p ~/.ssh'
    - 'chmod 700 ~/.ssh'
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - ssh-keyscan $TEST_SERVER_IP >> ~/.ssh/known_hosts

.test: &test
  stage: test
  tags:
    - ai-docker
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_KEY" | base64 -d)
    - 'mkdir -p ~/.ssh'
    - 'chmod 700 ~/.ssh'
    - ssh-keyscan $TEST_SERVER_IP >> ~/.ssh/known_hosts
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts

build-job-app:
  <<: *build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:app -f Dockerfile.gunicorn .
    - docker push $CI_REGISTRY_IMAGE:app

delivery-test:
  <<: *delivery
  script:
    - 'scp -i <(echo "$SSH_KEY" | base64 -d) docker-compose-dev.yml $TEST_SERVER:~/itmo-query-dev/docker-compose.yml'
    - 'scp -i <(echo "$SSH_KEY" | base64 -d) $ENV_FILE_TEST $TEST_SERVER:~/itmo-query-dev/.env'
    - >
      ssh $TEST_SERVER "
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin &&
      docker pull $CI_REGISTRY_IMAGE:app &&
      docker tag $CI_REGISTRY_IMAGE:app itmo_query
      "


deploy-test:
  <<: *deploy
  script:
    - >
      ssh $TEST_SERVER "
      cd itmo-query-dev &&
      docker compose up -d
      "

#test-job-app:
#  <<: *test
#  script:
#    - echo "Checking /app directory"
#    - ssh $TEST_SERVER 'docker exec -e PYTHONPATH=/app itmo_query ls -al /app'
#    - echo "Running tests"
#    - ssh $TEST_SERVER 'docker exec -e PYTHONPATH=/app/tests itmo_query pytest'


delivery-prod:
  <<: *delivery
  script:
    - 'scp -i <(echo "$SSH_KEY" | base64 -d) docker-compose-dev.yml $PROD_SERVER:~/itmo-query-prod/docker-compose.yml'
    - 'scp -i <(echo "$SSH_KEY" | base64 -d) $ENV_FILE_PROD $PROD_SERVER:~/itmo-query-prod/.env'
    - >
      ssh $PROD_SERVER "
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin &&
      docker pull $CI_REGISTRY_IMAGE:app &&
      docker tag $CI_REGISTRY_IMAGE:app itmo_query &&
      "
  only:
    - main

deploy-prod:
  <<: *deploy
  script:
    - >
      ssh $PROD_SERVER "
      cd itmo-query-prod &&
      docker compose up -d
      "
  only:
    - main
